Implement project
GordonOtieno/react-capstone pull request #2
Opened 2022-10-05 17:49 UTC by GordonOtieno

**Implemented Covid19 tracker**
- Created about componets.
- Created details components.
- Created redux store and configured the store.
- Implemented routings.
- Implemented test with jest library.
- Followed ducks filling methods.
- Solved linters errors.
- Recorded a video for the capstone: https://www.loom.com/share/0fc7a6b0645841c98e80bd017e8f36a0

2022-10-05 19:36 UTC, codecaiine requested changes
Hi @GordonOtieno , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-05 19:36 UTC, codecaiine commented on README.md
- [ ] When I click on your live demo link, nothing is not displaying we have a white page. Please fix it in order to make your project work as expected :+1: 
![Screenshot from 2022-10-05 18-40-25](https://user-images.githubusercontent.com/6615394/194137861-17849ac0-6c9e-4c36-a0d5-40e51af5b1f6.png)

2022-10-05 19:36 UTC, codecaiine commented on src/components/home/Home.js
> +};
- [ ] Good job so far  :+1:  But in your live demo your Home page doesn't have a list of categories that could be filtered using a given parameter for the example **category name.** :cry: Please fix it cause it is part of your project requirement  :+1: 
Check the example below :arrow_down: 
![Screenshot from 2022-10-05 18-49-49](https://user-images.githubusercontent.com/6615394/194139630-038c25cc-bcf7-429c-8978-244f86bf103e.jpg)
![Screenshot from 2022-10-05 18-51-27](https://user-images.githubusercontent.com/6615394/194139638-a7323aef-38c1-4dea-8c0c-9153c305e6e7.jpg)

2022-10-05 19:36 UTC, codecaiine commented on src/components/home/Home.js
> +};
- [ ] As required on the project [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=You%20should%20filter%20the%20data%20that%20you%20retrieve%20from%20the%20API%20using%20a%20Filter%20stateless%20component.), Please make sure that this component (which filters the data from the API) stateless and move this state to the parent component which is Home.js and pass it as a prop . :+1:

2022-10-06 09:44 UTC, GordonOtieno commented on README.md
@codecaiine It will update once I merge to dev branch. This is happening because I deployed dev branch in netllfy yet empty as at now.

2022-10-06 10:51 UTC, dasileker approved these changes
### **Hi @GordonOtieno,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 
### **Note**
- Please ensure that the live demo link status change I know it has a working link, but the title says `coming soon` but it should open the live link or something like that.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 13:43 UTC, merged